// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Jhoj3qrkD0yn01a3lBldWSVbbVg1H58',
    appId: '1:517159404131:web:89a183026d64d0fb4aee56',
    messagingSenderId: '517159404131',
    projectId: 'panther-mania',
    authDomain: 'panther-mania.firebaseapp.com',
    storageBucket: 'panther-mania.appspot.com',
    measurementId: 'G-0DWX4J2F97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOf72cz9fIIYrYnB40zApoEGKVsv207Q0',
    appId: '1:517159404131:android:81a5a5c1f3bddbe44aee56',
    messagingSenderId: '517159404131',
    projectId: 'panther-mania',
    storageBucket: 'panther-mania.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCozHLr7jcftaamvHQ9XmfRoyeYh0vBd4I',
    appId: '1:517159404131:ios:f5ec45d623c714304aee56',
    messagingSenderId: '517159404131',
    projectId: 'panther-mania',
    storageBucket: 'panther-mania.appspot.com',
    iosBundleId: 'com.example.pantherMania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCozHLr7jcftaamvHQ9XmfRoyeYh0vBd4I',
    appId: '1:517159404131:ios:0ca742188cc614504aee56',
    messagingSenderId: '517159404131',
    projectId: 'panther-mania',
    storageBucket: 'panther-mania.appspot.com',
    iosBundleId: 'com.example.pantherMania.RunnerTests',
  );
}
